/**
 * The SDLC is a set of files and scripts, so it is tested like one.
 *
 * docs/sdlc.md describes an artifact chain, five hooks, three merge tiers (unless
 * sdlc.json says `tiers: false`) and a review policy. Each of those is a file in this
 * repo, and each rule about them is checked here — the hook scripts by actually running
 * them with a piped payload, because a hook that "blocks pnpm add" and does not is worse
 * than no hook: everyone assumes it is there. GENERATED by `run-sdlc adopt`; the expectations come from sdlc.json.
 */
import { spawnSync } from 'node:child_process';
import { accessSync, constants, existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { describe, expect, it, vi } from 'vitest';

// The hook cases spawn bash + python3 per sample; under a full suite's parallel load one
// sample can take >1 s, so the 5 s default trips. File-local, not a global config change.
vi.setConfig({ testTimeout: 120_000 });

const ROOT = resolve(__dirname, '..');
const cfg = JSON.parse(readFileSync(join(ROOT, 'sdlc.json'), 'utf8')) as {
  changesDir: string;
  designsDir: string;
  verify: string;
  verifyDirty: string[];
  lintOnEdit: Record<string, string>;
  blocked: { match: string; message: string; samples: string[] }[];
  codeowners: string[];
  toolsCommand: string;
  tiers?: boolean;
};
const CHANGES = join(ROOT, cfg.changesDir ?? 'changes');
const ARCHIVE = join(CHANGES, 'archive');
const HOOKS = join(ROOT, '.claude', 'hooks');
const SETTINGS = join(ROOT, '.claude', 'settings.json');
// sdlc.json `tiers` (default true). Off: one owner, no Ship/Show/Ask, and none of its files.
const TIERS_ON = cfg.tiers !== false;
const TIER_FILES = ['.github/workflows/ship-show-ask.yml', 'scripts/ship_show_ask.py', '.github/tiers.json', '.github/CODEOWNERS'];
const TIERS = (
  TIERS_ON ? JSON.parse(readFileSync(join(ROOT, '.github', 'tiers.json'), 'utf8')) : { order: [], ask: [], show: [], ship: [] }
) as {
  order: string[];
  ask: string[];
  show: string[];
  ship: string[];
};

const INTENT_SECTIONS = ['## Problem', '## Proposed outcome', '## Affected users and systems', '## Constraints', '## Open questions'];
const PLAN_SECTIONS = ['## Order of work', '## Done', '## Revisions'];
// <created>-<KEY>-<slug>, and <created>-<slug> when the change has no Linear issue.
// Open and archived folders have the same shape: archiving moves the folder, it never renames it.
const CHANGE_DIR = /^(\d{4}-\d{2}-\d{2})-(?:([A-Z][A-Z0-9]+-\d+)-)?([a-z0-9][a-z0-9-]*)$/;

function dirs(parent: string): string[] {
  if (!existsSync(parent)) return [];
  return readdirSync(parent, { withFileTypes: true })
    .filter((d) => d.isDirectory() && d.name !== 'archive')
    .map((d) => d.name)
    .sort();
}

// The archive nests by <year>/<year-month>/ so it stays readable past a few hundred
// changes, the way docs/designs/ already does. Both layouts are walked: a repo that has
// not run `adopt` since the migration still has a flat archive, and its history is not
// wrong, just older. A directory is a change when its NAME matches CHANGE_DIR; anything
// else at these two levels is a year or a month bucket.
function archiveChanges(parent: string, depth = 2): [string, string][] {
  if (!existsSync(parent)) return [];
  const out: [string, string][] = [];
  for (const d of readdirSync(parent, { withFileTypes: true })) {
    if (!d.isDirectory()) continue;
    if (CHANGE_DIR.test(d.name)) out.push([parent, d.name]);
    else if (depth > 0) out.push(...archiveChanges(join(parent, d.name), depth - 1));
  }
  return out.sort((a, b) => a[1].localeCompare(b[1]));
}

function frontmatter(path: string): Record<string, string> {
  const text = readFileSync(path, 'utf8');
  const m = /^---\n([\s\S]*?)\n---\n/.exec(text);
  expect(m, `${path} has no YAML frontmatter`).toBeTruthy();
  const out: Record<string, string> = {};
  for (const line of m![1].split('\n')) {
    const i = line.indexOf(':');
    if (i > 0) out[line.slice(0, i).trim()] = line.slice(i + 1).trim();
  }
  return out;
}

/**
 * The `/goal` step 6 hands over, pulled out of an approved plan.
 *
 * It is a committed section rather than a chat message because a handover that lives in
 * one message is one that gets skipped with nothing downstream able to tell: the folder,
 * the PR and every other assertion here look complete without it. That is what happened
 * on 2026-09-18 — a document-shaped change wrote its artifact during planning, so step 6
 * had nothing left to hand over, and nobody noticed until the user asked for the `/goal`.
 *
 * `none — <why>` counts. A change whose deliverable IS the diff never had a build to hand
 * over, and saying so is a decision; leaving the section blank is a skip.
 */
function goalHandover(plan: string): string {
  const body = plan.split('## Goal handover')[1] ?? '';
  return body
    .split(/^## /m)[0]
    .split('\n')
    .filter((l) => !l.trimStart().startsWith('<') && !l.trimStart().startsWith('```'))
    .join('\n')
    .trim();
}

/** Without GIT_* so a run from a git hook never acts on the outer repo. */
function cleanEnv(): NodeJS.ProcessEnv {
  // Cast: Next.js augments ProcessEnv with a required NODE_ENV, which a filtered copy cannot prove.
  return Object.fromEntries(Object.entries(process.env).filter(([k]) => !k.startsWith('GIT_'))) as NodeJS.ProcessEnv;
}

/** Merge extra variables onto the clean environment for one spawn. */
function envWith(extra: Record<string, string>): NodeJS.ProcessEnv {
  return { ...cleanEnv(), ...extra } as NodeJS.ProcessEnv;
}

function runHook(script: string, payload: unknown, env: Record<string, string> = {}) {
  return spawnSync(join(HOOKS, script), [], {
    input: JSON.stringify(payload),
    encoding: 'utf8',
    env: envWith({ CLAUDE_PROJECT_DIR: ROOT, ...env }),
    timeout: 120_000,
  });
}

function tmp(name: string): string {
  const dir = join(tmpdir(), `sdlc-${process.pid}-${name}-${Date.now()}`);
  mkdirSync(dir, { recursive: true });
  return dir;
}

// --- designs and changes -------------------------------------------------------------

function checkChange(parent: string, id: string, archived: boolean) {
  const dir = join(parent, id);
  const parts = CHANGE_DIR.exec(id);
  const date = parts?.[1] ?? '';
  const key = parts?.[2] ?? '';
  const slug = parts?.[3] ?? '';
  it(`${id} carries facts.md and plan.md`, () => {
    expect(id).toMatch(CHANGE_DIR);
    for (const a of ['facts.md', 'plan.md']) expect(existsSync(join(dir, a)), a).toBe(true);
  });
  it(`${id}: frontmatter names its issue, its change and its design`, () => {
    for (const a of ['intent.md', 'facts.md', 'plan.md'].filter((a) => existsSync(join(dir, a)))) {
      const fm = frontmatter(join(dir, a));
      expect(fm.linear, `${a}: linear`).toBe(key || 'none');
      // Only for open changes: a folder archived before the date prefix existed carries its
      // ARCHIVE date in the name, and renaming merged history to fix that buys nothing.
      if (!archived) expect(fm.created, `${a}: created must match the date in the folder name`).toBe(date);
      expect(fm.change, `${a}: change`).toBe(id);
      expect(fm.design, `${a}: design`).toBeTruthy();
      if (fm.design !== 'null') expect(existsSync(join(ROOT, fm.design)), `${a}: design ${fm.design} does not exist`).toBe(true);
      if (archived) expect(fm.archived_at, `${a}: archived_at`).toMatch(/^\d{4}-\d{2}-\d{2}$/);
    }
  });
  it(`${id}: intent has the playbook sections, plan has order of work, Done and Revisions`, () => {
    if (existsSync(join(dir, 'intent.md'))) {
      const text = readFileSync(join(dir, 'intent.md'), 'utf8');
      expect(INTENT_SECTIONS.filter((s) => !text.includes(s))).toEqual([]);
    }
    const plan = readFileSync(join(dir, 'plan.md'), 'utf8');
    expect(PLAN_SECTIONS.filter((s) => !plan.includes(s))).toEqual([]);
  });
  it(`${id}: an approved plan hands its /goal over`, () => {
    // ARCHIVED CHANGES ARE EXEMPT, and that is why this is its own test rather than one
    // more entry in PLAN_SECTIONS. An archived folder is an immutable record — "moved
    // verbatim, never renamed" — so a newly required section applied to history fails
    // every change ever shipped. It did: 61 tests, across every folder in omr-leadhub's
    // archive, the first time this ran. The rule is for work going forward; history is
    // evidence, not a target.
    if (archived) return;
    // And only once the gate has approved it. A draft has nothing to hand over yet, and
    // failing one would make the gate impossible to reach.
    if (frontmatter(join(dir, 'plan.md')).status !== 'approved') return;
    const plan = readFileSync(join(dir, 'plan.md'), 'utf8');
    expect(goalHandover(plan), `${id}: ## Goal handover is missing or empty. Put the /goal from step 6 there, or "none — <why>".`).not.toBe(
      '',
    );
  });
  it(`${id}: a plan stands on approved facts, and the intent decision is recorded`, () => {
    // The backstop for chain-gate.sh. The hook refuses these writes while they can still be
    // fixed; this catches a folder that reached the repo without the hook — CI, another
    // machine, a repo adopted mid-change. Archived folders are exempt for the same reason
    // the handover rule exempts them: history is evidence, not a target.
    if (archived) return;
    // And only once the plan is approved, exactly like the handover rule above. A draft
    // plan beside draft facts is the legitimate in-flight state — facts are reviewed, then
    // the plan is written against them — and failing it would make the chain unreachable.
    // adopt's own seeded first change is the proof: it ships both files as drafts.
    if (frontmatter(join(dir, 'plan.md')).status !== 'approved') return;
    expect(
      frontmatter(join(dir, 'facts.md')).status,
      `${id}: plan.md exists but facts.md is not approved. Facts are reviewed before a plan is written against them.`,
    ).toBe('approved');
    const decisions = join(dir, 'decisions.json');
    const recorded =
      existsSync(join(dir, 'intent.md')) ||
      (existsSync(decisions) && String(JSON.parse(readFileSync(decisions, 'utf8')).intent ?? '').startsWith('skip'));
    expect(
      recorded,
      `${id}: no intent.md and no recorded skip. Write the intent, or record why it was skipped in decisions.json — a silent skip and a forgotten one look identical.`,
    ).toBe(true);
  });
  it(`${id}: its design lists it under Milestones`, () => {
    const fm = frontmatter(join(dir, 'plan.md'));
    if (fm.design === 'null') return;
    const design = readFileSync(join(ROOT, fm.design), 'utf8');
    expect(design.includes(slug), `${fm.design} does not mention ${slug}`).toBe(true);
  });
}

describe('changes', () => {
  for (const id of dirs(CHANGES)) checkChange(CHANGES, id, false);
  for (const [parent, id] of archiveChanges(ARCHIVE)) checkChange(parent, id, true);
  it('has at least one change — the chain was adopted by running it on itself', () => {
    expect(dirs(CHANGES).length + archiveChanges(ARCHIVE).length).toBeGreaterThan(0);
  });
  it('keeps no plans or handovers in .claude/plans', () => {
    const plans = join(ROOT, '.claude', 'plans');
    expect(!existsSync(plans) || readdirSync(plans).length === 0, '.claude/plans/ is scratch; use the change folder').toBe(true);
  });
});

// --- hooks: registered, executable, doing what docs/sdlc.md says ---------------------

// Pairs, not a record keyed by event: PreToolUse carries two hooks -- gate-bash.sh for what
// sdlc.json blocks, chain-gate.sh for the chain's own gates -- and a record kept only one.
const EXPECTED_HOOKS: [string, string][] = [
  ['SessionStart', 'session-check.sh'],
  ['PermissionRequest', 'plan-gate.sh'],
  ['PreToolUse', 'gate-bash.sh'],
  ['PreToolUse', 'chain-gate.sh'],
  ['PostToolUse', 'lint-on-edit.sh'],
  ['Stop', 'verify-on-stop.sh'],
];
const EXPECTED_DENY = ['Read(.env*)', 'Read(**/secrets/**)', 'Read(**/.secrets/**)'];

describe('settings.json', () => {
  const settings = JSON.parse(readFileSync(SETTINGS, 'utf8'));
  it('denies secrets and registers every hook', () => {
    for (const d of EXPECTED_DENY) expect(settings.permissions.deny).toContain(d);
    for (const [event, script] of EXPECTED_HOOKS) {
      const commands = (settings.hooks[event] as { hooks: { command: string }[] }[]).flatMap((g) => g.hooks.map((h) => h.command));
      expect(
        commands.some((c) => c.includes(script)),
        `${event} does not run ${script}`,
      ).toBe(true);
      expect(existsSync(join(HOOKS, script)), `${script} missing`).toBe(true);
      expect(() => accessSync(join(HOOKS, script), constants.X_OK), `${script} not executable`).not.toThrow();
    }
  });
  it('tracks the hook files despite a global gitignore', () => {
    const tracked = spawnSync('git', ['ls-files', '.claude/settings.json', '.claude/hooks', 'sdlc.json'], {
      cwd: ROOT,
      encoding: 'utf8',
      env: envWith({}),
    }).stdout.split(/\s+/);
    const expected = [
      '.claude/settings.json',
      'sdlc.json',
      '.claude/hooks/sdlc-config.sh',
      ...EXPECTED_HOOKS.map(([, s]) => `.claude/hooks/${s}`),
    ];
    expect(expected.filter((e) => !tracked.includes(e))).toEqual([]);
  });
});

describe('gate-bash', () => {
  // Every blocked rule carries sample commands in sdlc.json and each is run through the
  // hook. A pattern nobody can trip is a pattern nobody notices breaking.
  for (const rule of cfg.blocked) {
    const cmds = rule.samples ?? [];
    it(`blocks ${cmds[0] ?? rule.match} with a route`, () => {
      expect(cmds.length, `no samples for pattern ${rule.match}`).toBeGreaterThan(0);
      for (const c of cmds) {
        const r = runHook('gate-bash.sh', { tool_input: { command: c } });
        expect(r.status, c).toBe(2);
        expect(r.stderr).toContain('BLOCKED');
      }
    });
  }
  it.each(['git add .', 'pnpm test', 'kubectl get pods', "echo 'pnpm add'", 'uv sync'])('lets %s through', (c) => {
    expect(runHook('gate-bash.sh', { tool_input: { command: c } }).status).toBe(0);
  });
});

// One unformatted line per language the test knows. The matching file comes from this repo's
// own `lintOnEdit` globs, so a repo that formats only Python is tested on Python.
const UGLY: Record<string, string> = {
  py: 'x = [1,2,3 ]\n',
  ts: 'const x = [1,2,3 ]\n',
  tsx: 'const x = [1,2,3 ]\n',
  js: 'const x = [1,2,3 ]\n',
  mjs: 'const x = [1,2,3 ]\n',
};
const LINT_GLOBS = Object.keys(cfg.lintOnEdit ?? {}).flatMap((k) => k.split(/\s+/).filter(Boolean));
const LINT_EXT = LINT_GLOBS.map((g) => /^\*\.(\w+)$/.exec(g)?.[1]).find((e) => !!e && e in UGLY);
const LINT_SKIP = !LINT_GLOBS.length
  ? 'sdlc.json lintOnEdit is empty'
  : !LINT_EXT
    ? `no known unformatted sample for any lintOnEdit glob (${LINT_GLOBS.join(' ')})`
    : '';

describe('lint-on-edit', () => {
  it.skipIf(!!LINT_SKIP)(`formats a matching file and leaves others alone${LINT_SKIP ? ` (skipped: ${LINT_SKIP})` : ''}`, () => {
    const ugly = UGLY[LINT_EXT!];
    const dir = tmp('lint');
    const matching = join(dir, `ugly.${LINT_EXT}`);
    writeFileSync(matching, ugly);
    const other = join(dir, 'notes.txt');
    writeFileSync(other, ugly);
    expect(runHook('lint-on-edit.sh', { tool_input: { file_path: matching } }).status).toBe(0);
    expect(runHook('lint-on-edit.sh', { tool_input: { file_path: other } }).status).toBe(0);
    expect(readFileSync(matching, 'utf8')).not.toBe(ugly);
    expect(readFileSync(other, 'utf8')).toBe(ugly);
  });
});

describe('plan-gate', () => {
  it('falls through without plannotator', () => {
    const r = runHook('plan-gate.sh', { tool_name: 'ExitPlanMode' }, { PATH: '/usr/bin:/bin', CLAUDE_CONFIG_DIR: tmp('cfg') });
    expect(r.status).toBe(0);
    expect(r.stdout).toBe('');
  });
  it('steps aside when the plugin owns the hook', () => {
    const dir = tmp('plugin');
    mkdirSync(join(dir, 'plugins'));
    writeFileSync(join(dir, 'plugins', 'installed_plugins.json'), '{"plugins": {"plannotator@plannotator": {}}}');
    const bin = join(dir, 'bin');
    mkdirSync(bin);
    writeFileSync(join(bin, 'plannotator'), '#!/bin/sh\necho SHOULD-NOT-RUN\nexit 7\n', {
      mode: 0o755,
    });
    const r = runHook('plan-gate.sh', { tool_name: 'ExitPlanMode' }, { PATH: `${bin}:/usr/bin:/bin`, CLAUDE_CONFIG_DIR: dir });
    expect(r.status).toBe(0);
    expect(r.stdout).not.toContain('SHOULD-NOT-RUN');
  });
});

describe('session-check', () => {
  it('names what is missing and the install command', () => {
    const r = runHook('session-check.sh', {}, { PATH: '/usr/bin:/bin', CLAUDE_CONFIG_DIR: tmp('sc') });
    expect(r.status).toBe(0);
    expect(r.stdout).toContain('plannotator binary');
    expect(r.stdout).toContain(cfg.toolsCommand);
  });
});

describe('verify-on-stop', () => {
  function repo(verifyExit: number): string {
    const dir = tmp('repo');
    const env = envWith({});
    spawnSync('git', ['init', '-q'], { cwd: dir, env });
    // The throwaway repo gets its own sdlc.json so `verify` is a script we control.
    writeFileSync(
      join(dir, 'sdlc.json'),
      JSON.stringify({
        verify: `sh -c 'echo verify-ran; exit ${verifyExit}'`,
        verifyDirty: ['*.ts'],
      }),
    );
    spawnSync('git', ['add', '.'], { cwd: dir, env });
    spawnSync('git', ['-c', 'user.name=t', '-c', 'user.email=t@t', 'commit', '-qm', 'init'], {
      cwd: dir,
      env,
    });
    return dir;
  }
  it('is a no-op without dirty source', () => {
    const dir = repo(1);
    writeFileSync(join(dir, 'README.md'), 'dirty but not source\n');
    const r = runHook('verify-on-stop.sh', { stop_hook_active: false }, { CLAUDE_PROJECT_DIR: dir });
    expect(r.status).toBe(0);
    expect(r.stderr).not.toContain('verify-ran');
  });
  it('blocks the stop when verify fails', () => {
    const dir = repo(1);
    writeFileSync(join(dir, 'x.ts'), 'export const x = 1;\n');
    const r = runHook('verify-on-stop.sh', { stop_hook_active: false }, { CLAUDE_PROJECT_DIR: dir });
    expect(r.status).toBe(2);
    expect(r.stderr).toContain('verify FAILED');
    expect(r.stderr).toContain('fix the code, not the test');
  });
  it('passes when verify passes', () => {
    const dir = repo(0);
    writeFileSync(join(dir, 'x.ts'), 'export const x = 1;\n');
    expect(runHook('verify-on-stop.sh', { stop_hook_active: false }, { CLAUDE_PROJECT_DIR: dir }).status).toBe(0);
  });
  it('never loops', () => {
    const dir = repo(1);
    writeFileSync(join(dir, 'x.ts'), 'export const x = 1;\n');
    expect(runHook('verify-on-stop.sh', { stop_hook_active: true }, { CLAUDE_PROJECT_DIR: dir }).status).toBe(0);
  });
});

// --- review policy and merge tiers -----------------------------------------------

describe('REVIEW.md', () => {
  it('has the playbook structure and the tally line', () => {
    const text = readFileSync(join(ROOT, 'REVIEW.md'), 'utf8');
    for (const h of ['## Passes', '## What Important means here', '## Cap the nits', '## Do not report']) expect(text).toContain(h);
    expect(text).toContain('IMPORTANT: <n>  NITS: <m>');
  });
});

/** A concrete path that a glob names: `k8s/**` → `k8s/x/y.txt`, `*.lock` → `x.lock`. */
function sample(glob: string): string {
  return glob.replace(/\*\*/g, 'x/y.txt').replace(/\*/g, 'x');
}

function classify(files: string[]): string {
  const r = spawnSync('python3', [join(ROOT, 'scripts', 'ship_show_ask.py'), 'classify', ...files], { encoding: 'utf8', cwd: ROOT });
  expect(r.status, r.stderr).toBe(0);
  return r.stdout.trim();
}

describe.skipIf(!TIERS_ON)('tiers', () => {
  it('orders ask, show, ship with ship as the catch-all', () => {
    expect(TIERS.order).toEqual(['ask', 'show', 'ship']);
    expect(TIERS.ship).toEqual(['**']);
  });
  it.each([
    [[], 'ship'],
    [['docs/sdlc.md'], 'ship'],
    [[`${cfg.changesDir}/REV-1-x/plan.md`, 'README.md'], 'ship'],
    [['.claude/hooks/gate-bash.sh'], 'ask'],
    [['.github/workflows/ci.yml'], 'ask'],
    [['REVIEW.md'], 'ask'],
    // One sample path per ask and show glob, derived from tiers.json itself.
    ...TIERS.ask.map((g) => [[sample(g)], 'ask'] as [string[], string]),
    ...TIERS.show.map((g) => [[sample(g)], 'show'] as [string[], string]),
    ...TIERS.show.map((g) => [[sample(g), sample(TIERS.ask[0])], 'ask'] as [string[], string]),
  ] as [string[], string][])('classifies %j as %s', (files, expected) => {
    expect(classify(files)).toBe(expected);
  });
  it('CODEOWNERS is exactly the ask tier, generated from sdlc.json', () => {
    const path = join(ROOT, '.github', 'CODEOWNERS');
    if (cfg.codeowners.length === 0) {
      expect(existsSync(path), 'no codeowners in sdlc.json, so no CODEOWNERS file').toBe(false);
      return;
    }
    const rules = readFileSync(path, 'utf8')
      .split('\n')
      .map((l) => l.split('#')[0].trim())
      .filter(Boolean)
      .map((l) => l.split(/\s+/));
    const normalise = (p: string) => (p.replace(/^\//, '').endsWith('/') ? p.replace(/^\//, '') + '**' : p.replace(/^\//, ''));
    expect(new Set(rules.map((r) => normalise(r[0])))).toEqual(new Set(TIERS.ask));
    for (const r of rules) expect(r.slice(1)).toEqual(cfg.codeowners);
  });
});

describe('docs and workflows', () => {
  it('exist and are linked from CLAUDE.md', () => {
    expect(existsSync(join(ROOT, 'docs', 'sdlc.md'))).toBe(true);
    expect(readFileSync(join(ROOT, 'CLAUDE.md'), 'utf8')).toContain('docs/sdlc.md');
    const claudeOn = (cfg as { claude?: boolean }).claude !== false;
    for (const wf of ['claude-review.yml', 'claude.yml', 'ci-triage.yml'])
      expect(existsSync(join(ROOT, '.github', 'workflows', wf)), `${wf} (sdlc.json claude=${claudeOn})`).toBe(claudeOn);
    for (const wf of ['ship-show-ask.yml'])
      expect(existsSync(join(ROOT, '.github', 'workflows', wf)), `${wf} (sdlc.json tiers=${TIERS_ON})`).toBe(TIERS_ON);
  });
  it.skipIf(TIERS_ON)('has none of the tier files when sdlc.json says tiers: false', () => {
    expect(TIER_FILES.filter((f) => existsSync(join(ROOT, f)))).toEqual([]);
  });
  it.skipIf(!TIERS_ON)('arms auto-merge with the App token, never github.token, in a job without checkout', () => {
    const text = readFileSync(join(ROOT, '.github', 'workflows', 'ship-show-ask.yml'), 'utf8');
    const arm = text.split('\n  arm:\n')[1].split('\n  notify:')[0];
    expect(arm).not.toContain('actions/checkout');
    expect(arm).toContain('GH_TOKEN: ${{ steps.app-token.outputs.token }}');
    expect(arm).not.toContain('GH_TOKEN: ${{ github.token }}');
  });
});
